# ---------------------------------
# Secret: credenciales MySQL
# ---------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: db-passwords

# Opaque: tipo genérico de secret (llaves arbitrarias base64)
type: Opaque

data:
  # Valor base64 del password root. ("root" en claro)
  mysql-root-password: cm9vdA==
